STD_PLUGIN := plugins/nucleus_fermi plugins/pion_beam plugins/brems \
	      plugins/hades plugins/dalitz_mod plugins/elementary \
	      plugins/eta_decays plugins/scatter_mod plugins/strangeness \
	      plugins/w_decays plugins/pdg_unigen plugins/beamline plugins/tools \
	      plugins/dalitz_radiative-corrections
