{
gROOT->Reset();

THtml html;

html.SetOutputDir("/u/hadeshyp/web-docs/pluto/v6.0");
//html.SetSourceDir("../src/");
//html.SetSourcePrefix("../");
html.MakeIndex("P*");
html.MakeClass( "PChannel" );
html.MakeClass( "PReaction" );
html.MakeClass( "PAngularDistribution" );
html.MakeClass( "PUtils"  );
html.MakeClass( "PData"  );
html.MakeClass( "PParticle"  );
html.MakeClass( "PFireball"  );
html.MakeClass( "PSaid"  );
html.MakeClass( "PChannel"  );
html.MakeClass( "PReaction"  );
html.MakeClass( "PFilter"  );
html.MakeClass( "PThermal"  );
html.MakeClass( "PDecayChannel"  );
html.MakeClass( "PDecayManager"  );
html.MakeClass( "PDataBase"  );
html.MakeClass( "PStdData"  );
html.MakeClass( "PStaticData"  );
html.MakeClass( "PMesh"  );
html.MakeClass( "PFileInput"  ); 
html.MakeClass( "PFileOutput"  );
html.MakeClass( "PDiLepton"  );
html.MakeClass( "PCross"  );
html.MakeClass( "PDistribution"  ); 
html.MakeClass( "PDebugFileOutput"  );
html.MakeClass( "PDistributionManager"  );
html.MakeClass( "PDalitzDistribution"  );
html.MakeClass( "PScatterDistribution"  );
html.MakeClass( "PChannelModel"  );
html.MakeClass( "PBreitWigner"  );
html.MakeClass( "PDynamicData"  );
html.MakeClass( "PHadronModel"  );
html.MakeClass( "PStdModels"  );
html.MakeClass( "PDalitzDecay"  );
html.MakeClass( "PHadronDecay"  );
html.MakeClass( "PHadronDecayM1"  );
html.MakeClass( "PHadronDecayM1N"  );
html.MakeClass( "PHadronDecayM2"  );
html.MakeClass( "PHadronDecayM3"  );
html.MakeClass( "PInclusiveModel"  );
html.MakeClass( "PEEDirectDecay"  );
html.MakeClass( "PMassSampling"  );
html.MakeClass( "PFixedDecay"  );
html.MakeClass( "PGenBod"  );
html.MakeClass( "PDeltaAngularDistribution"  ); 
html.MakeClass( "PPiOmegaAngularDistribution"  );
html.MakeClass( "PFermiMomentum"  );
html.MakeClass( "PFermiMomentumDD"  );
html.MakeClass( "PComplexBreitWigner"  );
html.MakeClass( "PValues"  );
html.MakeClass( "PBulkInterface"  ); 
html.MakeClass( "PPlutoBulkDecay"  );
html.MakeClass( "PEmbeddedParticles"  );
html.MakeClass( "PBeamSmearing"  );
html.MakeClass( "PPythiaBulkDecay"  );
html.MakeClass( "PTCrossWeight"  );
html.MakeClass( "PEtaModels"  );
html.MakeClass( "PAdaptiveMesh"  );
html.MakeClass( "PAdaptiveMeshN"  );
html.MakeClass( "PBatch"  );
html.MakeClass( "PProjector"  );
html.MakeClass( "PVertexFile"  );
html.MakeClass( "PFunction"  );
html.MakeClass( "PDistributionManagerUtil"  );
html.MakeClass( "PDistributionCollection"  );
html.MakeClass( "PNNFSI"  );
html.MakeClass( "PElementaryPlugin"  );		  
html.MakeClass( "PDalitzModPlugin"  );
html.MakeClass( "PDeltaDalitzKrivoruchenko"  );
html.MakeClass( "PFormula"  );
html.MakeClass( "PPropagator"  );
html.MakeClass( "PHadesParticleSmearer"  );
html.MakeClass( "PArray"  );
html.MakeClass( "PCommandList"  );
html.MakeClass( "PF1"  );
html.MakeClass( "PF2"  );
html.MakeClass( "PF3"  );
html.MakeClass( "PSplash"  );
html.MakeClass( "PUtilsREngine"  );
html.MakeClass( "PFixedProduction"  );
html.MakeClass( "PSimpleVMDFF"  );
html.MakeClass( "PAnyDistribution"  );
html.MakeClass( "PDensityMatrix"  );

html.MakeClass( "PBeamLineSimulation");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PBremsstrahlung");
html.MakeClass( "PBremsstrahlungPlugin");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PElementaryPlugin");
html.MakeClass( "PNNFSI");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PEtaDecaysPlugin");
html.MakeClass( "PEtaDoubleDalitz");
html.MakeClass( "PEtaDoubleDalitzEnv");
html.MakeClass( "PEtaDoubleDalitzFF");
html.MakeClass( "PEtaPiPiDilepton");
html.MakeClass( "PEtaPiPiDileptonMass");
html.MakeClass( "PEtaPiPiGamma");
html.MakeClass( "PFairGenerator");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PHadesParticleSmearer");
html.MakeClass( "PHGeantOutput");
html.MakeClass( "PHUrAddon");
html.MakeClass( "PHUrCollisionHeader");
html.MakeClass( "PHUrDilep");
html.MakeClass( "PHUrEventHeader");
html.MakeClass( "PHUrParticle");
html.MakeClass( "PHUrReader");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PHadesParticleSmearer");
html.MakeClass( "PHGeantOutput");
html.MakeClass( "PHUrAddon");
html.MakeClass( "PHUrCollisionHeader");
html.MakeClass( "PHUrDilep");
html.MakeClass( "PHUrEventHeader");
html.MakeClass( "PHUrParticle");
html.MakeClass( "PHUrReader");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PPDGPlugin");
html.MakeClass( "PUniGenInput");
html.MakeClass( "UEvent");
html.MakeClass( "UParticle");
html.MakeClass( "URun");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PPionBeamAmplitude");
html.MakeClass( "PPionBeamPlugin");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PSaidLowEnergy");
html.MakeClass( "PSaidPN");
html.MakeClass( "PScatterCrossSection");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "PStrangenessPlugin");
html.MakeClass( "PGammaConversion");
html.MakeClass( "PDistributionManager.mod");
html.MakeClass( "POmega3Pi");
html.Convert("hello_world.C" , " <b>Hello World</b>");
html.Convert("printParticle.C" , " Access and print basic particle properties");
html.Convert("parse_eta.C" , " <b>Setting up reactions:</b> Use the one-liner parser to produce eta Dalitz events");
html.Convert("analyze_eta_dalitz.C" , " Analyze the eta Dalitz output file");
html.Convert("complete_eta.C" , " Use the long example to produce eta Dalitz events");
html.Convert("w_dalitz.C" , " Use the long example to produce omega Dalitz events");
html.Convert("dp_delta_dalitz.C" , " Produce Delta Dalitz events in the quasi-free n+p (d+p) collision");
html.Convert("dp_w_dalitz.C" , " Omega Dalitz with decay manager in the p+d reaction");
html.Convert("thermal_rho.C" , " <b>Thermal macros (PFireball):</b> Test thermal source of rho's");
html.Convert("useAngularDistribution.C" , " <b>Angular distribution interface:</b> Add user-defined angular distributions");
html.Convert("anaAngularDistribution.C" , " Analyze the polar angle as created with useAngularDistribution");
html.Convert("test_batch.C" , " <b>The event loop interface:</b> Make histograms in one single line without ana macro with the PBatch script language");
html.Convert("batch_filters.C" , " Demonstrate how batch scripting can be used to define filters");
html.Convert("batch_write_ntuple.C" , " Writing TNtuple(s) and ASCII files");
html.Convert("batch_read_ntuple.C" , " Re-read an TNtuple (from the example above) and make a histogram");
html.Convert("batch_read_ASCII.C" , " Re-read the ASCII-file from batch_write_ntuple.C and make a bulk decay");
html.Convert("ntuple_to_pparticle.C" , " Convert an TNtuple (from the example above) to a PParticle and make a bulk decay");
html.Convert("eta_pileup.C" , " Using a batch script to simulate pileup");
html.Convert("PHadesAcc.C" , " <UserClass> Very small acceptance filter (setting variables for batch) including opening angle.");
html.Convert("embeddedParticles.C" , " <PEmbeddedParticles> Adds embedded particles in the eta Dalitz decay");
html.Convert("bulk_decay.C" , " <PPlutoBulkDecay> Demonstrates the bulk decay option");
html.Convert("use_DensityMatrix.C" , " Using the density matrix");
html.Convert("use_Do_in_PChannel.C" , " Using scripting in a PChannel");
html.Convert("beamsmearing_example.C" , " <b>Usage of Pluto build-in templates:</b> beam smearing");
html.Convert("pp_collider_elastic.C" , " pp elastic scattering with different beam tilts");
html.Convert("user_mass.C" , " Play with the mass shape of a dummy resonance");
html.Convert("user_w_dalitz_ff.C" , " Demo using the batch syntax to change the omega form factor");
html.Convert("user_eta_3pi_decay.C" , " Demo using the batch syntax to change the Dalitz plot eta -> 3pi");
html.Convert("user_eta_3pi_decay_histo.C" , " Demo using a histogram to change the Dalitz plot eta -> 3pi");
html.Convert("use_eta_generator.C" , " <b>Usage of weights/generators:</B> another way of eta Dalitz simulation");
html.Convert("ana_eta_generator.C" , " Compare eta Dalitz using weights with parse_eta.C");
html.Convert("rho_mass_shape.C" , " Choosing the rho0 -> e+e- partial width model");
html.Convert("PFermiNucleus.C" , " <b>Quasi-free reactions:</b> A (dummy) model for fermi samping inside a nucleus");
html.Convert("piA.C" , " <PFermiNucleus, PBeamSmearing> Quasi-free pi+A scattering, including beam smearing");
html.Convert("fermi_dd.C" , " <PFermiMomentumDD> The scattering of two nucleons inside deuterons");
html.Convert("pp_cocktail_1.25.C" , " <b>Total cross sections:</b> The pp cocktail at 1.25GeV");
html.Convert("dp_cocktail_1.25.C" , " <b>Total cross sections:</b> The dp cocktail at 1.25AGeV");
html.Convert("pp_cocktail_35.C" , " <b>Cocktails for 3.5GeV:</b> the pp reaction");
html.Convert("pA_cocktail_35.C" , " Thermal source model of p+nucleus 3.5 AGeV ");
html.Convert("make_demo_pfilter.C" , " <b>Virtual detectors and batch packs</b> This macro makes a demo filter root file");
html.Convert("use_demo_pfilter.C" , " Use the filter file from above");
html.Convert("multiple_branches.C" , " Using more than one ROOT TBranch to store undistorted sim particles");
html.Convert("plugin_makeEmbeddedParticlesVertexHGeant.C" , " <UserClass> Embedded particles with vertex info and seq-nr for HADES");
html.Convert("plugin_urqmd_f15_input.C" , "");
html.Convert("plugin_Li7_breakup_macro.C" , " Breakup Reaction for Li7");
html.Convert("plugin_proton_Li7_macro.C" , " Example for a p + 7Li reaction");
html.Convert("plugin_fermi_rescattering.C" , " Two-step process (phi in medium -> K K -> K K_scatter)");
html.Convert("plugin_unigen_input.C" , " Reading an UniGen file");
html.Convert("plugin_using_pdg_code.C" , " Using the pdg-code");
html.Convert("plugin_pion_beam_example.C" , " Example how to use the pion beam plugin");
html.Convert("plugin_pp_ela_4e.C" , " Low-energy pp scattering");
html.Convert("plugin_cross_section_example.C" , " Example for a 2-body scattering with total and differential cross sections");
html.Convert("plugin_w_hadronic_test.C" , " Test macro for omega -> pi+pi-pi0");
}
